/**
 ******************************************************************************
 * @file    main.c
 * @author  Auto-generated by STM32CubeIDE
 * @version V1.0
 * @brief   Default main function.
 ******************************************************************************
 */



#include <stdio.h>
#include "uart_driver.h"
#include <stdint.h>

#define F_CPU 16000000U

void timer(char*);

// main
// This program is a timer that counts down
int main(void){
	//The first index of the lcd array will store the char pressed
	//the second index will be 0 to be able to terminate the string
	char lcd[2] = {'\0', '\0'};

	// boolean for when the user presses the # button to start the timer
	int start = 0;

	//initializes LCD
	lcd_init();

	//infinite loop to keep running program
	while (1 != 0) {

	//String of characters user entered to be sent
	char send[50];

	//index is to keep track of chars in send[]
	int index = 0;

	//places getchars into a send[]
	while(start != 1) {
	//returns the char pressed
	char key = keypad_getchar();
	lcd[0] = key;
	lcd_print_string(lcd);
	send[index] = key;

	//if the key '#' isnt pressed, chars will keep on
	//being added to send[]
	//or else the send[] "time" will be sent over to start
	//the timer
	if(key == '#') {
		lcd_clear();
		start = 1;
		send[index] = '\0';
	}
	index++;
	//delays 250ms so the program doesn't take multiple inputs
	//at once by accident
	delay_ms(250);
	}
	timer(send);
	lcd_clear();
	lcd_home();
	start = 0;
	}
	return 0;
}

//Function: The timer will begin
//and count down showing on LCD
//param: time in which user sent over
//return: nothing
void timer(char* time) {
	int timer = atoi(time);
	while (timer >= 0) {
		//delay for 1 sec for countdown
		lcd_print_num(timer);
		delay_s(1);
		lcd_home();
		timer--;
	}
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////

