/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/



#include <stdio.h>
#include "uart_driver.h"
#include <stdint.h>


#define F_CPU 16000000UL

/* main
 * This program gives the user the ability to read/dump from and write to
 * a desired memory address
 */
int main(void){
	init_usart2(19200,F_CPU);
	printf("%s", "Type \"help\" to assist you input correctly \n\r");
	//infinite loop
	while (1 != 0) {
	char user_input[50];
    fgets(user_input, sizeof(user_input), stdin);
 of enter key
    char* input = strtok(user_input, "\n");

	//splits input by spaces
    //retrieves command
	char* token = strtok(input, " ");
	char command[3];
	sprintf(command, "%s", token);

	//retrieves address
	token = strtok(NULL, " ");
	char address[33];
	sprintf(address, "%s", token);
	uint32_t address_convert = (uint32_t)strtoll(address, NULL, 16);

	//retrives value
	//wm, value is to be written in selected address
	//dm, value is for number of bytes to be dumped
	token = strtok(NULL, " ");
	char value[10];
	int default_bytes = 16;
	sprintf(value, "%s", token);
	uint32_t value_converted = (uint32_t)strtoll(value, NULL, 16);
	uint32_t *address_data = (uint32_t) address_convert;

    if((command[0] == 'r')&& (command[1] == 'm')) {
    	printf("Hex:%X, Dec:%d \n\r", *address_data, *address_data);

    } else if ((command[0] == 'w')&&(command[1] == 'm')) {
    	*address_data = value_converted;

    } else if ((command[0] == 'd')&&(command[1] == 'm')) {
    	if (value_converted == 0){
    		value_converted = default_bytes;
    	}
    	int word_per_line = 4;
    	printf("%X: ", address_data);
    	//repeats while there are more bytes to be read or
    	//the line needs to be filled with 16 bytes
    	while ((value_converted > 0) || (word_per_line != 0)){
    		if (word_per_line == 0) {
    			printf("\n\r%\X: ", address_data);
    			word_per_line = 4;
    		}
    		printf("%08X ", *address_data);
    		address_data ++;
    		//decreases by 4 because there are 4 bytes per word
    		value_converted -= 4;
    		word_per_line --;
    	}
    	printf("\n\r");

    } else if ((command[0] == 'h')&&(command[1] == 'e')&&
    		(command[2] == 'l')&& (command[3] == 'p')) {
    	printf("There are 3 commands, rm, wm, and dm.\r\n");
    	printf("rm is to read memory from a given address.\n\r");
    	printf("wm is to write memory in hex to a given address.\n\r");
    	printf("dm is to dump memory from a given address.\n\r");
    	printf("Type the command, then press space and enter an address.\n\r");
    	printf("The address should be enterd in hex form and can add/exclude 0x\n\r");
    	printf("Lastly, press space again and choose a value.\n\r");
    	printf("If command wm is chosen, the value will be placed into the given address.\n\r");
    	printf("If command dm is chosen, the value is the number of bytes to dump.\n\r");
    	printf("The value has no usefulness for the rm command.\n\r");
    } else {
    	printf("Error, retype\n\r");
    }
	}

	// never return
	for(;;){}

	return 0;
}
    //get rid

